### ISSUE TITLE
Źle wykonany szkielet aplikacji

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#14]
https://github.com/lukasz99933/Bowling/blob/fb74b4d0e2c97b1e272ceb4277af23514f6dee38/bowling.hpp#L10

Pod zadaniem szkielet nie chodziło o przygotowanie zestawu funkcji. To ma wyjsć dopiero w trakcie pisania testów w TDD. Chodziło o ustawienie struktury plików w repozytorium (katalog na testy, katalog na kod) i odpowiedniego systemu budowania

**Comment by bogkra** [comment]
poprawione
