### ISSUE TITLE
const string & s będzie wydajniejsza, bo unikamy kopiowania obiektów

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#20]
https://github.com/lukasz99933/Bowling/blob/aa35aeb7f7e0c722fb85724cbff11923b7373ebe/src/bowling.hpp#L13

**Comment by bogkra** [comment]
nad const string& się zastanawiałem, ale myślałem, że chyba przesada. Jeśli tu &, to kiedy bez? Dla danych typu bool, int ?

**Comment by ziobron** [comment]
Dla typów prostych jak int, bool, double, char referencja jest zbędna. Dla bardziej złożonych jest to optymalizacja, bo nie dość że mówisz kompilatorowi że obiekt będzie tylko do odczytu to jeszcze nie robisz dodatkowej kopii podczas przekazywania go jako argument. A wywołanie konstruktora i destruktora coś tam kosztuje.
