### ISSUE TITLE
wejście raczej niepotrzebne

### ISSUE THREAD

**Issue by bogkra** [lukasz99933/Bowling#24]
https://github.com/lukasz99933/Bowling/blob/e478816f5f0651460f40f19ee8b76ac68c7504f5/src/bowling.hpp#L14
wydaje mi się, że w zasadzie można od razu korzystać z prywatnego vector<string> tokens, nie ma potrzeby kopiować do wejścia, w dodatku w ten sposób łatwiej się te metody obsługuje z zewnątrz, bo teraz piszesz:
    game.fillTokens("X|7/|9-|X|-8|8/|-6|X|X|X||81");
    auto tokens = game.getTokens();
    ASSERT_TRUE(game.validateIsCorrect(tokens));
a wtedy by można było po prostu:
    game.fillTokens("X|7/|9-|X|-8|8/|-6|X|X|X||81");
    ASSERT_TRUE(game.validateIsCorrect());

**Comment by ziobron** [comment]
+1
Bardzo słuszny komentarz

**Comment by ziobron** [comment]
Nazwa validateIsCorrect jakoś sama w sobie jest nadmiarowa. Przy okazji można ją skrócić do samego validate() albo validateTokens()

**Comment by bogkra** [comment]
też tak myślałem, ale pewnie chodziło o to, że podkreśla zwracanie bool ;) - vaidateTokens będzie lepsze, bo będzie wiadomo, CO jest walidowane (przecież mogą być różne rzeczy)
