### ISSUE TITLE
#include <iostream> w tym pliku nagłówkowym nie jest potrzebne

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#28]
https://github.com/lukasz99933/Bowling/blob/fbfb73322477f2b71e3f4881b736978b9fc884e6/src/bowling.hpp#L3

Strumieni używacie w pliku .cpp, więc tam trzeba przenieść tego includa.

**Comment by bogkra** [comment]
ale bez tego się string nie kompiluje... :-)

**Comment by bogkra** [comment]
zmienione na <string>

**Comment by ziobron** [comment]
No to `#include <string> `
