### ISSUE TITLE
Nadajcie coś znaczące nazwy tym przykładom

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#29]
https://github.com/lukasz99933/Bowling/blob/fbfb73322477f2b71e3f4881b736978b9fc884e6/test/bowlingTest.cpp#L12

Np twelveStrikes, tenNines, tenFivesAndSpares albo coś w tym stylu
Ale sam pomysł z wpisaniem ich do bowlingTest bardzo dobry 👍

**Comment by ziobron** [comment]
Nazwy testów też trzeba będzie odpowiednio dopasować, aby coś znaczyły.

**Comment by bogkra** [comment]
to miało znaczyć: example of Xs (czyli że same X)

**Comment by bogkra** [comment]
w sumie strikes będzie lepsze

**Comment by bogkra** [comment]
albo bestPossible :)

**Comment by bogkra** [comment]
teraz chyba ładniej?... :) :
 const string perfectScore = "X|X|X|X|X|X|X|X|X|X||XX";
 const string alwaysAlmostPerfect = "9-|9-|9-|9-|9-|9-|9-|9-|9-|9-||";
 const string twentyOneFives = "5/|5/|5/|5/|5/|5/|5/|5/|5/|5/||5";
 const string mixed = "X|7/|9-|X|-8|8/|-6|X|X|X||81";
 const string perfectNoob = "--|--|--|--|--|--|--|--|--|--||";

**Comment by ziobron** [comment]
Ładniej :)

**Comment by bogkra** [comment]
mnie się zwłaszcza podoba twentyOneFives, bo trzeba się trochę zmóżdżyć, czemu akurat tyle... ;)

**Comment by bogkra** [comment]
- po polsku mogłoby być oczkoPiatek ;)
