### ISSUE TITLE
Też wystarczy prostszy przykład

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#31]
https://github.com/lukasz99933/Bowling/blob/fbfb73322477f2b71e3f4881b736978b9fc884e6/test/bowlingTest.cpp#L145

Nie komplikujcie przykładów testowych, powinny być możliwie jak najprostsze, w których dany błąd wystąpi, czyli tutaj coś takiego `a|9` (być może nawet samo `a`?)

**Comment by bogkra** [comment]
raczej chodziło o przetestowanie czwartego tokena, teoretycznie najprostszy przypadek to byłoby |||

**Comment by bogkra** [comment]
aha i to nie jest błąd, fill po prostu wypełnia nie patrząc na sensowność danych w tokenie, to ma robić walidacja
