### ISSUE TITLE
Te wszystkie poprawne przykłady dla translate akurat można scalić w jeden test.

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#32]
https://github.com/lukasz99933/Bowling/blob/fbfb73322477f2b71e3f4881b736978b9fc884e6/test/bowlingTest.cpp#L198

Możecie dodać też drugi w którym będą niepoprawne przypadki np translate('a')

**Comment by bogkra** [comment]
moim zdaniem od tego jest walidacja (piszę oczywiście o negatywnych przypadkach)

**Comment by bogkra** [comment]
chyba że... potraktować to jako wstępną walidację...
