### ISSUE TITLE
48 nic nie mówi, lepiej po prostu '0'

### ISSUE THREAD

**Issue by bogkra** [lukasz99933/Bowling#36]
https://github.com/lukasz99933/Bowling/blob/c5650fd5d117e88aed80cfb7a1b993d7bfe4a46e/src/bowling.cpp#L119

**Comment by bartek56** [comment]
48 by zamienić char na int. spójrz w tablicę ASCII

**Comment by bogkra** [comment]
po co mam spoglądać? przy '0' nie musisz nic tłumaczyć ani nigdzie zaglądać.

**Comment by bogkra** [comment]
ponadto sposób z '0' zadziała nawet jeśli ktoś np. za 30 lat w jakimś systemie wpadnie na pomysł zmiany kodowania z ASCII na jakiś inny... ;)

**Comment by ziobron** [comment]
+1, słuszna uwaga. '0' mówi więcej niż 48 :)
