### ISSUE TITLE
Refactor sprawdzania zawartości wektorów

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#47]
https://github.com/lukasz99933/Bowling/blob/c5650fd5d117e88aed80cfb7a1b993d7bfe4a46e/test/bowlingTest.cpp#L176-L186

Nie potrzeba aż 10 linii do sprawdzenia zawartości wektora :)
Takie coś jest w google teście:

//checks that vector v is {5, 10, 15}
ASSERT_THAT(v, ElementsAre(5, 10, 15));

**Comment by ziobron** [comment]
Podbijam to issue. Jest dość ważne. Lepiej będzie się czytało testy.

**Comment by bogkra** [comment]
"ElementsAre has a limit of 10 elements. " :D

**Comment by bogkra** [comment]
nie akceptuje tego ASSERT_THAT, hm

**Comment by ziobron** [comment]
Możesz zrobić drugi vector:
```
std::vector<int> expected = {0, 0, 0, ..., 0}
ASSERT_EQ(expected, result);
```

**Comment by bogkra** [comment]
kurde, WŁAŚNIE TAK zrobiłem przed chwilą, a nie przeczytałem wczoraj, ale heca! :D
