### ISSUE TITLE
bowling.hpp~ to plik tymczasowy, nie powinno go być w repo

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#49]
https://github.com/lukasz99933/Bowling/blob/84b3dff9e8101ab43f7bf60aae462fca8fc6c393/src/bowling.hpp~#L1

**Comment by bogkra** [comment]
a jak się kasuje?

**Comment by bogkra** [comment]
jest kosz, ale wyrzuca warning "you must be on the branch"
