### ISSUE TITLE
Nigdy nie komentujemy już działających testów!

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#50]
https://github.com/lukasz99933/Bowling/blob/62a664ae859552a60d69a183c362fe790db55961/test/bowlingTest.cpp#L170-L242

Nie, nie, nie! Czegoś takiego nigdy nie robimy. Coś co kiedyś działało musi dalej działać. Nie ma mowy, aby wyłączyć jakieś testy, bo nam nie przechodzą.

**Comment by bartek56** [comment]
te testy są od metody, która nie była już używana (została usunięta), więc "usunąłem" te testy. Powinienem zostawić metody wraz z testami, które już nie biorą udziału w działaniu programu ?

**Comment by ziobron** [comment]
Jeśli metoda została zastąpiona inną, to testy trzeba odpowienio przepisać, aby działały z nową metodą. 
W każdymbądź razie scenariuszy testowych usuwać się nie powinno. Jeśli zmienił się design kodu, to scenariusze testowe trzeba dostosować.

**Comment by bartek56** [comment]
No i przerobiona metoda jest prywatna i używana jest w metodzie która jest testowana, zatem kod jest pokryty testami, a usunąłem to, co nie jest używane w programie, a więc powtórze pytanie: czy kod który nie wpływa na funkcjonalność programu i jest pokryty testami należy nie usuwać?

**Comment by ziobron** [comment]
Pokryte jest, ale innymi testami. Ważne aby chociaż w tej fazie
przejściowej pozostawić dokładnie te same scenariusze testowe. Jak będzie
wtedy z nimi zielono i wyjdzie na to że są one duplikacją to wtedy w fazie
Refactor można je usunąć. Na Discordzie opisałem mniej więcej jak trzeba by
było to zrobić.
Nie odbieraj tego jako atak na Ciebie (bo programiści jakoś lubią traktować
swój kod jak swoje dziecko). Kierunek zmian jest bardzo dobry i w tę stronę
to ma iść, tylko ja wskazuję w jaki sposób bezpiecznie to zrobić, aby potem
nic nie wybuchło.

śr., 28.03.2018, 07:19 użytkownik Bartosz <notifications@github.com>
napisał:

**Comment by bartek56** [comment]
Programiści muszą bronić swojego kodu ;-)
