### ISSUE TITLE
Własne skrypty nie powinny być w repo

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#51]
https://github.com/lukasz99933/Bowling/blob/7751a66618a34af1800320b667b14b3c8f8b3761/push#L1-L3

Pewnie nikt inny tego nie używa, bo nawet nie wie o ich istnieniu. W repozytorium ma być sam kod i tylko to co jest z nim związane, nic więcej. U mnie w pracy niedawno znaleźli wkomitowaną binarkę Firefoxa przez Chińczyków w 3 różne miejsca.

Poza tym taki skrypt może być niebezpieczny, bo nie sprawdzasz nawet jakie zmiany robisz, tylko od razu push.

**Comment by bogkra** [comment]
wg DRY wrzucanie instalki Firefoxa jest złe, bo instalka jest w innym miejscu i jest aktualizowana, natomiast dobre jest wrzucenie skryptu instalującego, a np. w PP zalecają tworzenie tooli ułatwiających pracę i udostępnianie ich. To, że nikt nie używa tego skryptu, to akurat bardzo prawdopodobne, bo i tak ostatnio nikt nic nie dodaje poza mną, ale mogę dodać info na czat. Skrypt jest "własny" chyba w sensie, w jakim kod też jest "własny", nie ma tu żadnych prywatnych ścieżek itp. Jeśli chodzi o sprawdzanie zmian - jeśli plik nie był zmieniany, nie poleci do commita, nawet jeśli użyję add. Przed commitem leci do edycji plik, w którym wpisuję jego nazwę i tam jest napisane, co było zmienione, co nie, i co leci do commita, jeśli się okaże, że jeszcze coś trzeba dorzucić, to wtedy oczywiście mogę przerwać skrypt i puścić adda i pusha osobno.
Akurat te skrypty mi się bardzo przydały, bo sekwencje komend wykonywałem z 70x, a z kompilacją jeszcze więcej

**Comment by bogkra** [comment]
a może takie rzeczy powinny być w jakimś innym miejscu?...
