### ISSUE TITLE
Zamiast pisać komenatrze którą funkcję testujemy można zrobić oddzielne Test Suite

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#54]
https://github.com/lukasz99933/Bowling/blob/7751a66618a34af1800320b667b14b3c8f8b3761/test/bowlingTest.cpp#L18-L20

TEST_F(bowlingFillFrameTest, emptyFrame) 
TEST_F(bowlingFillFrameTest, test2) 
TEST_F(bowlingCountTest, test1) 
TEST_F(bowlingCountTest, test2) 
TEST_F(bowlingCountTest, test3) 
...

**Comment by bogkra** [comment]
po testach parametrowych już nieaktualne
