### ISSUE TITLE
Rozbicie na mniejsze przypadki

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#56]
https://github.com/lukasz99933/Bowling/blob/7751a66618a34af1800320b667b14b3c8f8b3761/test/bowlingTest.cpp#L98-L108

To można rozbić na pojedyncze przypadki, które nietrudno nazwać np. TooManyCharacters, InvalidCharacter

**Comment by bogkra** [comment]
no właśnie to jest 3x invalidCharacters ( = NotCorrectSymbols)
1) a  - żle
2) Y - żle
3) dobrze
TooManyCharacters było jako validationTooManyDigits)

pierwszy przykład w sumie nie jest prawidłowy, bo nie jest jednostkowy...

**Comment by bogkra** [comment]
właściwie zamiast pierwszego lepiej zrobić test na || w złym miejscu
