### ISSUE TITLE
Nie może być rzeczy public for tests only

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#59]
https://github.com/lukasz99933/Bowling/blob/7751a66618a34af1800320b667b14b3c8f8b3761/src/bowling.hpp#L17

Nigdy nie zmienia się kodu pod testy. Taki komentarz świadczy o złym projekcie kodu.
Podpowiedź: a może klasa Bowling robi za dużo i można ją podzielić?

**Comment by bogkra** [comment]
a co da podzielenie ws. public?

**Comment by bogkra** [comment]
dałem do public :)
