### ISSUE TITLE
Walidacja tokenów "3pkt"

### ISSUE THREAD

**Issue by bogkra** [lukasz99933/Bowling#6]

**Comment by ziobron** [comment]
A dodajcie jeszcze przypadek takiego tokenu do testów:
|999|

**Comment by bogkra** [comment]
no właśnie, będzie niby ok, walidacja tu jest dość skomplikowana wbrew pozorom, jeśli potraktowana szczegółowo. Tylko pytanie czy w ogóle trzeba było ją robić?! :D Z treści zadania chyba to nie wynika

**Comment by ziobron** [comment]
Sami ją dodaliście :)
Ja jestem tylko prostym klientem, który chce aplikację, która policzy mi punkty. Nie znam się na programowaniu, wy wiecie co tam musi być ;) Ale jak coś mi nie będzie działało to będę wam suszył głowę :D
