### ISSUE TITLE
Wszystkie implementacje w cpp mają być

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#61]
https://github.com/lukasz99933/Bowling/blob/7751a66618a34af1800320b667b14b3c8f8b3761/src/bowling.hpp#L31

Nawet jak są takie krótkie. Trzeba konsekwentnie, bo potem ktoś będzie szukał implementacji w cpp, nie znajdzie i stwierdzi że magia się dzieje albo że napisze drugą i nie będzie wiedział czemu ma problemy z kompilacją.

Tylko implementacje funkcji szablonowych mogą (a właściwie muszą) być w plikach nagłówkowych.

**Comment by bogkra** [comment]
tak mi przypomniał gettera, że wrzuciłem do hpp ;)
