### ISSUE TITLE
Tutaj powinien być typ std::string jako parametr

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#62]
https://github.com/lukasz99933/Bowling/blob/7751a66618a34af1800320b667b14b3c8f8b3761/src/bowling.hpp#L16

Wiem że Frame to to samo, ale reprezentuje logicznie coś innego. Można robić różne magie, aby kompilator np pokazywał nam błąd, pomimo tego, że mamy pod spodem takie same rzeczy. Są to tzw. strong types. Przykłady: https://www.fluentcpp.com/2016/12/08/strong-types-for-strong-interfaces/
Ale tego nie wymagam. Podobno w C++20 mają być już w języku strong types.

**Comment by bogkra** [comment]
strong types od zawsze były w Pascalu. Popieram ;) Zawsze mnie w c++ denerwowało, że nie widać tego na etapie kompilacji, a potem się szuka nie wiadomo gdzie błędu

**Comment by bogkra** [comment]
z tym Frame w tym miejscu ewidentnie się rozpędziłem
