### ISSUE TITLE
std::accumulate

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#65]
https://github.com/lukasz99933/Bowling/blob/7751a66618a34af1800320b667b14b3c8f8b3761/src/bowling.cpp#L97-L101

**Comment by bogkra** [comment]
zrobione, ale brzydko :( :
  int i=0;
  return accumulate(frames.begin(), prev(frames.end()), 0, 
              [&](int sum, Frame frame) 
              { 
                return sum + countExtra(i++);
                if (frame.length()>0) 
                  i++;  
              });

zamienię jednak te i na iteratory
