### ISSUE TITLE
Też std::accumulate

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#66]
https://github.com/lukasz99933/Bowling/blob/7751a66618a34af1800320b667b14b3c8f8b3761/src/bowling.cpp#L119-L122

**Comment by bogkra** [comment]
zrobiłem tak:
  return accumulate(standardFrames().begin(), standardFrames().end(), 0, 
              [=](int sum, Frame frame) 
              { 
                return sum + countSeparateScore(frame);
              });

ale czy to na pewno prościej? ;)

**Comment by bogkra** [comment]
ha! ze standardFrames() jest segmentation fault
poprawione:
  return accumulate(frames.begin(), prev(frames.end()), 0, 
              [=](int sum, Frame frame) 
              { 
                return sum + countSeparateScore(frame);
              });
