### ISSUE TITLE
Magiczna wartość

### ISSUE THREAD

**Issue by ziobron** [lukasz99933/Bowling#67]
https://github.com/lukasz99933/Bowling/blob/7751a66618a34af1800320b667b14b3c8f8b3761/src/bowling.cpp#L130

A co nam mówi to -1? Ktoś może zdobyć -1 punkt i w sumie to może być tak potraktowane.
Tutaj trzeba użyć wyjątków, aby dać znać komuś, kto będzie korzystał z klasy Bowling, że poszło coś nie tak.
Do testowania czy wyjątki poleciały też są specjalne funkcje w Google tescie jak ASSERT_THROW

**Comment by bogkra** [comment]
oj tam od razu magiczna, z ASSERT_THROW próbowałem, nie wyszło, więc na razie hulajnoga ;)

**Comment by bogkra** [comment]
a swoją drogą -1 pkt w kręglach... to dopiero żenada... ;)
