### ISSUE TITLE
Bonusy "5pkt"

### ISSUE THREAD

**Issue by bogkra** [lukasz99933/Bowling#8]

**Comment by bartek56** [comment]
@bogkra  mam pytanie do metody countBonuses(). Rozumiałem to jako liczenie punktów tylko z bonusów. Ja wykonałem liczenie punktów z rundy, nie licząc już punktów za bonusy.
Po dokładnym analizowaniu kodu, zrozumiałem, że ta metody w kolekcji vector zawiera punkty z rundy, więc trochę to koliduje ze sobą. Mogę zrobić liczenie bonusów, lecz wtedy twoja metoda będzie nieużywana. Czy przerobisz tą metodę tylko na liczenie punktów z bonusów, czy mam rozwinąć swój kod?

**Comment by bogkra** [comment]
W countBonuses liczę wyłącznie bonusy,  nie wiem,  skąd wywnioskowałeś,  że coś jeszcze
